FROM ubuntu:jammy
ENV DEBIAN_FRONTEND noninteractive

RUN apt update -q && apt install -qy \
    texlive-full \
    texlive-latex-extra \
    biber \
    python3-pygments gnuplot \
    make git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /data
VOLUME ["/data"]
